sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t kirillkaiumov/multi-client ./client
  - docker build -t kirillkaiumov/multi-nginx ./nginx
  - docker build -t kirillkaiumov/multi-server ./server
  - docker build -t kirillkaiumov/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kirillkaiumov/multi-client
  - docker push kirillkaiumov/multi-nginx
  - docker push kirillkaiumov/multi-server
  - docker push kirillkaiumov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-511648242690
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
